version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    mem_limit: 2g
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2g
        reservations:
          cpus: "0.25"
          memory: 1g
